### ISSUE TITLE
Station Art not Showing on Browse

### ISSUE THREAD

**Issue by abates** [mopidy/mopidy-pandora#74]
Station art images are not appearing when browsing mopidy-pandora stations.  I'll work on this and submit a pull request when I have it figured out.

**Comment by abates** [comment]
Exception details:

```python
ERROR    2020-07-03 14:43:36,063 [252:Core-7] mopidy.core.library
  PandoraBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cachetools/cache.py", line 39, in __getitem__
    return self.__data[key]
KeyError: 'pandora:genres'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mopidy_pandora/library.py", line 144, in get_images
    track = self.lookup_pandora_track(uri)
  File "/usr/lib/python3.8/site-packages/mopidy_pandora/library.py", line 235, in lookup_pandora_track
    return self.pandora_track_cache[uri].track
  File "/usr/lib/python3.8/site-packages/cachetools/lru.py", line 14, in __getitem__
    value = cache_getitem(self, key)
  File "/usr/lib/python3.8/site-packages/cachetools/cache.py", line 41, in __getitem__
    return self.__missing__(key)
  File "/usr/lib/python3.8/site-packages/cachetools/cache.py", line 68, in __missing__
    raise KeyError(key)
KeyError: 'pandora:genres'

```

**Comment by abates** [comment]
@jodal can you please review the PR for this issue?
